export enum MetaActions {
  APP_BOOTSTRAP = "APP_BOOTSTRAP",
  APP_BOOTSTRAP_SUCCESS = "APP_BOOTSTRAP_SUCCESS",
  APP_BOOTSTRAP_FAILED = "APP_BOOTSTRAP_FAILED"
}

export enum TestActions {
  INCREMENT = "INCREMENT",
  INCREMENT_FAILURE = "INCREMENT_FAILURE",
  INCREMENT_SUCCESS = "INCREMENT_SUCCESS"
}
